- src/components.d.ts
- src/components/biggive-button/biggive-button.tsx
- src/components/biggive-button/test/biggive-button.spec.tsx
Reverts thebiggive/components#54
1. I'm having to revert the PR because it's not needed - we can simply use [routerLink] in Angular to make use of the Angular router for DON-604, so a custom even emit is not needed.
2. It's a breaking change
> Revert "Tom components 20221116"

- angular/projects/components/package.json
Reverts thebiggive/components#95
Reason: Angular front-end throws the following error when running `npm update`:
```
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "^14.1.0|^15.0.4" of package "@angular/common@^14.1.0|^15.0.4": Tags may not have any characters that encodeURIComponent encodes.
```
> Revert "DON-667: Declare compatibility with Angular 15 as well as 14 to allow…"

- .circleci/config.yml
- angular/projects/components/package.json
- package-lock.json
- package.json
- scripts/create-version.sh
This should mean we no longer need to create any tags or manually update any versions to publish components to NPM. Instead whenever a commit is merged to `main` (or to the branch of this PR) a version number is auto generated based on the time such as `v202301201120.0.0` (i.e. 11:20 on Jan 20 2022), and published to NPM.
> Com 14 auto versioning

- src/components/biggive-branded-image/biggive-branded-image.scss
- src/components/biggive-campaign-card-filter-grid/biggive-campaign-card-filter-grid.scss
- src/components/biggive-campaign-card/biggive-campaign-card.scss
- src/components/biggive-campaign-highlights/biggive-campaign-highlights.scss
- src/components/biggive-footer/biggive-footer.scss
- src/components/biggive-form-field-select-option/biggive-form-field-select-option.scss
- src/components/biggive-form-field-select/biggive-form-field-select.scss
- src/components/biggive-header/biggive-header.scss
- src/components/biggive-heading/biggive-heading.scss
- src/components/biggive-hero-image/biggive-hero-image.scss
- src/components/biggive-main-menu/biggive-main-menu.scss
- src/components/biggive-page-section/biggive-page-section.scss
- src/components/biggive-search/biggive-search.scss
- src/globals/mixins.scss
- src/globals/variables.scss
When discussing designs with the team no-one says "Can you make that colour primary" or "I preferred it in brand 4". We talk about blue and yellow. This refactor should make it easier to map between those discussions and code.
> Refactor: Rename colour variables to have more understandable names

- src/components/biggive-main-menu/biggive-main-menu.scss
Previously the Match Funding opportunties menu was too close to the right edge of the viewport, so that when you open the sub menu the sub-submen items get pushed of the edge of the screen.
Before:
After:
Separate PRs will be needed to pull changes into the donate-frontend and wordpress.
> DON-739: Space out main nav to make open subsubmenu items fully visible

- src/components/biggive-main-menu/biggive-main-menu.tsx
This was broken in commit 73c286d with the shift to hard-coded menu content in this repo. Not sure why we now need to find the elements in the shadowRoot. Querying them directly from the host returns an empty node list.
Menu now appears as below in mobile version of this library's index file and is usable again:
There is still a visual regression compared to the old good version below, that this PR doesn't fix, but it fixes the reported bug which is the most urgent thing to fix. For reference this is the old version of the menu:
> COM-55: Fix touch events on mobile menu

- src/components/biggive-main-menu/biggive-main-menu.tsx
I've been working on Donate with the updates from https://github.com/thebiggive/components/pull/154 and a reduction in offset workarounds in Donate itself.
However Firefox, when resizing down from desktop size to a slightly smaller one, still has a very broken rendering edge case which occurs intermittently. It seems to correlate with an extremely high calculated body padding number, so this PR caps the maximum offset to make it a bit less broken for now.
When the bug occurs, the empty space usually first appears as the menu's blue, then sometimes appears white later. So far I can't replicate it on Chrome or Safari running the same code.
> Add a maximum offset to deal with resize edge case

- src/components/biggive-campaign-card-filter-grid/biggive-campaign-card-filter-grid.tsx
All things on the campaign grid I broke last week
in an attempt to make the linter happy. Hopefully `as`, while a bit hackier, will do the job better than we had before and not crash it!
> Resolve various `instanceof` breaks

- src/globals/mixins.scss
Before (with uncommited changes in index html):
After:
> DON-812: Thicken select drop down border to match text input border

- src/components/biggive-campaign-card-filter-grid/biggive-campaign-card-filter-grid.tsx
Bug found in donate-fronted, also visible in the index.html file here
Before:
After:
We were displaying an empty button for every possible filter even if not selected.
Bug found during QA of DON-836 but not actually related to the Angular upgrade.
> Fix filter grid display bug (bug was never in prod)

- src/components.d.ts
- src/components/biggive-article-card/biggive-article-card.scss
- src/components/biggive-basic-card/biggive-basic-card.scss
- src/components/biggive-basic-card/biggive-basic-card.tsx
- src/components/biggive-basic-card/readme.md
- src/components/biggive-basic-card/test/biggive-basic-card.spec.tsx
- src/components/biggive-formatted-text/biggive-formatted-text.scss
Reverts thebiggive/components#229
This change was intended for use in wordpress but unintentally also changed the card layout on donate homepage.
> Revert "Updates"

- package-lock.json
- package.json
- src/components.d.ts
Reverts thebiggive/components#258
due to an error in [CircleCI](https://app.circleci.com/pipelines/github/thebiggive/components/1204/workflows/23519b40-244d-4516-bba2-b0c88003e7bb/jobs/1799), which we tried to fix with @bdsl
```
Building Angular Package
------------------------------------------------------------------------------
Building entry point '@biggive/components-angular'
------------------------------------------------------------------------------
- Compiling with Angular sources in Ivy partial compilation mode.
✖ Compiling with Angular sources in Ivy partial compilation mode.
projects/components/src/lib/stencil-generated/components.ts:7:15 - error TS2305: Module '"@biggive/components/dist/components"' has no exported member 'Components'.
7 import type { Components } from …
```
> Revert "COM-50: upgrade stencil/core and stencil/sass"

- .circleci/config.yml
(Hopefully!)
Based on:
```
[ ERROR ]  Could not find Chrome (ver. 114.0.5735.133).
This can occur if either 1. you did not perform
an installation before running the script (e.g.
`npm install`) or 2. your cache path is
incorrectly configured (which is:
/home/circleci/.cache/puppeteer). For (2), check
out our guide on configuring puppeteer at
https://pptr.dev/guides/configuration.
```
> COM-88 – fix puppeteer 2nd run cache problems

- .circleci/config.yml
Previously this only ran when we were ready to actually publish to NPM. Running for all commits will help avoid merging anything that breaks the angular build
> COM-50: Run Angular build on all commits in CircleCI

- .circleci/config.yml
Otherwise we never get to publish the new version of components so it can be used in the build of components-angular
> COM-50: Allow builds to go-ahead during stencil major version upgrade

- angular/package.json
- package-lock.json
- package.json
- src/components.d.ts
Reverts thebiggive/components#261
Haven't been able to get publishing components-angular to work on `main` since merging PR 261, despite clearing the caches, so sadly reverting. Looks like my theory of why it didn't work last week may be wrong.
> Revert "Revert "Revert "COM-50: upgrade stencil/core and stencil/sass"""

- src/components/biggive-button/biggive-button.scss
Forgot to do this as part of https://github.com/thebiggive/components/pull/280 . 
This button should show as pink not black.
Does seem like our colour code is really error prone as we have to add the new colour in a lot of places. Maybe next time we're adding a colour it will be worth refactoring to make it so there's just one (or not as many as there are now) place to add the next new colour.
Could also think about making it so the WP editing interface displays the names of the colours at the same time.
> WPD-168: Add styling for Arts for Impact pink button

- src/components/biggive-cookie-banner/biggive-cookie-banner.scss
- src/components/biggive-cookie-banner/biggive-cookie-banner.tsx
Before:
After:
I'd prefer the corners to be rounded, but that isn't an option in our popup component and I'm not sure it's worth building it just for this. I tried to get this a bit closer to what @thebiggive/devs suggested on Jira, plus match the appearance of the popup we have already for filter selection in explore shown below:
> DON-783: Adjust style of cookie consent popup form

- src/components/biggive-popup/biggive-popup.tsx
- src/components/biggive-popup/test/biggive-popup.spec.tsx
Popup is currently used for selecting filters in the explore page, and is about to be used for selecting cookie preferences
> DON-783: Set focus on popup when opened

- readme.md
As few changes as possible in a commit. I want to see whether the hash mentioned in dist/esm/loader.js changes from a19ad098 and how pulling this into wordpress affects things.
Apparently it does not change - but then as no actual js files are different that may not matter.
> WPD-162: Update readme to check how this affects wordpress

- src/components/biggive-back-to-top/biggive-back-to-top.tsx
- src/components/biggive-footer/biggive-footer.tsx
Hopefully fixes loading assets like the FR logo in footer in full `dist` load contexts like the "sorry" page
> INFRA-122 - use `getAssetPath()` as per readme

- src/components/biggive-footer/biggive-footer.tsx
- src/components/biggive-footer/test/biggive-footer.spec.tsx
Alt text now matches the text that's inside the image, omitting the actual FR logo.
Image can be seen at
https://raw.githubusercontent.com/thebiggive/components/main/src/assets/images/fundraising-regulator.png
Although in components merging to main doesn't release to production automatically for frontend or wordpress, it does actually release directly to production for the "sorry" page, which is what I'm most interested in here and doesn't have a build step and pulls from NPM in the browser.
> INFRA-122: Fix alt text for fundraising regulator footer image

- angular/projects/components/src/lib/components.module.ts
- src/components/biggive-totalizer/biggive-totalizer.tsx
Pretty much per the 'Ionic way' in the latest docs at https://stenciljs.com/docs/angular#registering-custom-elements
This seems to become necessary with as-documented paths and Stencil v4. (I did a proof of concept calling a similar fn in Donate itself first, and the principle seems to work.)
> COM-50 – get the Angular component library module to bootstrap its own elements

- .npmrc
Before making this change today I was constantly getting "code E401 npm ERR! Incorrect or missing password." when running npm install.
Not sure why we haven't needed to fix this before now.
> Fix fontawesom NPM registry details

- src/components/biggive-campaign-card-filter-grid/biggive-campaign-card-filter-grid.tsx
- src/components/biggive-campaign-card-filter-grid/test/biggive-campaign-card-filter-grid.spec.tsx
Currently FE is passing Most Raised with two capitals but the component is only expecting one capital. Hard to be sure ot always get this matched up properly so doing a case insenstive comparison here
Should fix this error:
> DON-970: Fix handling of order by prop with unexpected casing

- package-lock.json
- package.json
Reverts thebiggive/components#527
That apparently made donate-frontend server side rendering hundreds of times slower - taking 15 seconds instead of just 0.1 seconds. I guess it must be something in the update to stencil 4.19.0.
> Revert "Bump the all-dependencies group across 1 directory with 11 updates"

- package-lock.json
- package.json
I think this may break FE as happened on Friday (15s initial load time) but I want to do it anyway to be sure. As soon as I see if it broke it I'll try to fix by updating to 4.19.1 and if that doesn't work going back to 4.18.3
> Update @stencil/core to 4.19.0

- src/components/biggive-text-input/biggive-text-input.scss
- src/components/biggive-text-input/biggive-text-input.tsx
- src/index.html
If the name requires multiple lines to render it will now take up vertical space on the page, pushing the actual input and everything below it down.
Screenshots below showing the components repo index page on a variety of page widths. Will need testing in frontend before we can know for sure if this is good. The only cases where the layout really doesn't work seem to be where the prompt has an extremely wide individual word.
> DON-976: Allow long names in text input prompts

- src/components/biggive-form-field-select/biggive-form-field-select.scss
- src/globals/mixins.scss
This works for the drop-down parts of the donate form. Not sure yet how we can do the text inputs, still needs thought, and if we can't find a way to make that work its possible we'll have to revert this since having focus displayed on the drop downs but not on text inputs might make things more confusing.
Will affect not only the donate form as the ticket is focused on but everything else that uses this select component, including the contact us form on the wordpress site. I think that's actually it for now.
> COM-99: Change form field select border from blue to coral when focused

- src/components/biggive-main-menu/biggive-main-menu.tsx
Hoping this may fix the issue, hard to tell as the issue only exists in hosted environments and I haven't been able to reproduce in local yet
See https://stenciljs.com/docs/component-lifecycle#componentdidload
> COM-101: Delay work on submenus to later in component lifecycle

- src/components/biggive-hero-image/biggive-hero-image.scss
- src/components/biggive-hero-image/biggive-hero-image.tsx
* Avoid 50px plus 45px double bottom margins if there are no buttons that require post-teaser space; keep just the `.content-wrap` 50px in that case
* Avoid 20px empty "slug" if there is no slug text and there is no champion logo which would otherwise look cramped against the title
> Hero vertical space tweaks

- src/components/biggive-grid/biggive-grid.scss
- src/components/biggive-grid/biggive-grid.stories.tsx
Avoid clipped words & improve squashed appearance. Staging before this change:
A review in Storybook (with updated sample copy) suggests there shouldn't be wider impact on layouts from the change. The example changes to 2 cols at similar viewport widths to the Donate example.
> Grid fix for large tablet & small desktop breakpoints

- src/components/biggive-hero-image/biggive-hero-image.scss
- src/components/biggive-hero-image/biggive-hero-image.tsx
- src/index.html
Currently when we do a server side render something (not sure what) that I think is part of our Stencil library inserts whitespace and comments that show the HYDRATE_CHILD_ID / c-id of various elements, e.g.:
<div c-id="44702.7.3.2" class="teaser">
Hi. We’re Big Give. Our match funding campaigns offer a unique opportunity for you to double the difference you can make in the world for the causes close to your heart.
</div>
This combined with our use of `whitespace: pre-wrap` removed here meant the layout of our main title and subtitle on the homepage was messed up in the SSR version of the page, and visible moved between rendering that and the client side rendered version.
So removing `pre-wrap` here and replacing with `<br/>` tags.
> DON-961: Fix hero image layout issue in server side render

- src/components/biggive-campaign-card/biggive-campaign-card.tsx
Issue listed as #3 in my comment on the ticket yesterday at 17:30
This fixes the immediate thing but I'm not very happy about it because we're likely to keep having to do similar fixes everywhere - looks like at least all stencil props that rely on data fetched at runtime are ending up undefined during the initial server side render
> COM-101: Fix 404 error fetching 'undefined' image in campaign card

- readme.md
- src/components/biggive-back-to-top/biggive-back-to-top.tsx
- src/components/biggive-footer/biggive-footer.tsx
Although this is a step away from the Stencil docs, we are seeing load problems with WordPress treating asset paths as relative so it seems worth a go.
> COM-101 – try prefix asset paths with /

- src/components/biggive-main-menu/biggive-main-menu.scss
- src/components/biggive-main-menu/biggive-main-menu.tsx
* Use `scrollHeight` to reduce the likelihood of mobile rendering in particular having intermittent bugs
* Remove the repaint after 1s as that didn't seem to fix things
* Cheat a bit by setting a 60px minimum offset
Looking at https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollHeight, it seems plausible that this property might be a little less sensitive to temporary aspects of the render like a scrollbar not existing yet at the moment body padding's first calculated.
> The scrollHeight value is equal to the minimum height the element would require in order to fit all the content in the viewport without using a vertical scrollbar.
Not certain at all but seems worth trying. This PR also adds logging for now, so we can get more of a sense of how much we are relying on the …
> COM-102 – adjust how we position content below the menu

- src/components/biggive-main-menu/biggive-main-menu.tsx
First half of CC24 redirect readiness.
> Main menu: update menu 'noredirect' dates for CC24; tidy up temporary logs

- src/components/biggive-footer/biggive-footer.stories.tsx
- src/components/biggive-footer/biggive-footer.tsx
- src/components/biggive-main-menu/biggive-main-menu.tsx
- src/components/biggive-main-menu/test/biggive-main-menu.spec.tsx
- src/components/biggive-social-icon/test/biggive-social-icon.spec.tsx
- src/util/fontawesome-icons.ts
Use new logo everywhere. Update our own socials to x.com versions.
Still use 'Twitter' in logo ARIA labels for screen readers etc. for now.
> DON-1095 – update Twitter/X branding

- .github/dependabot.yml
Until https://github.com/stenciljs/core/issues/6206 fixed
> Turn off Stencil auto update PRs that would use 4.26+, for now

- src/components.d.ts
- src/components/philco-footer/philco-footer.tsx
- src/components/philco-footer/readme.md
- src/util/helper-methods.ts
Previously URLs were remnants of copy & paste from BG components, these are now my best guesses of what we may actually want the URls to be.
Also deleted the cookie preference centre link as I don't expect we will have such for Philco
> COM-104: Use actually reasonable URLs in philco header/footer links

- src/components/biggive-button/biggive-button.scss
Bug introduced in 453cc4b9e14207 - I think that
was just a line changed and committed by mistake.
Fixed button looks like this in storybook:
> Fixes a bug where black buttons had dark grey text

- src/components.d.ts
- src/components/biggive-form-field-select/biggive-form-field-select.tsx
- src/components/biggive-form-field-select/readme.md
- src/components/biggive-form-field-select/test/biggive-form-field-select.spec.tsx
> Set an accessible label for selects that rely on a placeholder value

- src/components.d.ts
- src/components/biggive-form-field-select/biggive-form-field-select.tsx
- src/components/biggive-form-field-select/readme.md
- src/components/biggive-form-field-select/test/biggive-form-field-select.spec.tsx
Story book is still not working I'm afraid but this should be easy to test at http://localhost:3939/pages/biggive.html 
Clicking the target icon for me in firefox opens the select node within the inspector
> COM-83: Add explicit label for select element

- src/components/philco-footer/philco-footer.tsx
See comments on ticket
Linked works on my local at http://localhost:3939/pages/philco.html
> Adjust link to philco guide

- src/globals/variables.scss
The names of these were wrong, meaning they could be selected but didn't actually work as backgrounds in WP.
> WPD-192: Fix ER colours

- src/globals/variables.scss
I also some code to test html to see all the ER colours so I could see that this fixes the dark green by didn't commit that
> WPD-192: Fix missing er-dark-green colour

- src/components/biggive-basic-card/biggive-basic-card.scss
- src/components/biggive-quote/biggive-quote.scss
- src/components/philco-footer/philco-footer.scss
- src/globals/mixins.scss
- src/globals/philco-variables.scss
My aim with the footer changes is to get things almost exactly as Production is again on desktop.
I slightly reduced vertical space in a couple of places on mobile where I thought it was a bit excessive, so that it's now like this in Firefox:
> WPD-195 – PhilCo header & footer fixes

- src/components/biggive-main-menu/biggive-main-menu.scss
Note that the logic activating the mobile view of the same menu is based on `@media (hover: hover)` – so there is a pre-existing issue that using a tiny viewport on a desktop device gives an unusable 2nd level menu. (I think with this change it becomes a bit more obviously broken but both are bad.) If you simulate mobile including pointer events then you get a working mobile menu, so I think this is probably OK to ignore for now.
> COM-106 – Fix `.sub-sub-menu` position on medium viewports
