.circleci/config.yml
angular/package-lock.json
angular/projects/components/src/public-api.ts
package-lock.json
readme.md
src/components/biggive-campaign-card/biggive-campaign-card.tsx
stencil.config.ts

And document all current build targets better

COM-9 – fix Angular build target

---

.circleci/config.yml
src/components.d.ts
src/components/biggive-campaign-card/readme.md
src/components/biggive-hero-image/biggive-hero-image.tsx
src/components/biggive-hero-image/readme.md
src/components/biggive-hero-image/test/biggive-hero-image.spec.tsx

And update types for this + campaign card

Hero: fix mainImage null safety

---

package-lock.json
src/components/biggive-button/biggive-button.stories.tsx
src/components/biggive-button/readme.md
src/components/biggive-campaign-card-filter-grid/biggive-campaign-card-filter-grid.tsx
src/components/biggive-campaign-card-filter-grid/readme.md
src/components/biggive-campaign-card-filter-grid/test/biggive-campaign-card-filter-grid.spec.tsx
src/components/biggive-search/biggive-search.tsx
src/components/biggive-search/readme.md

Use `<biggive-button />` consistently

---

src/components.d.ts
src/components/biggive-campaign-card/biggive-campaign-card.tsx
src/components/biggive-campaign-card/readme.md
src/components/biggive-campaign-card/test/biggive-campaign-card.spec.tsx
src/components/biggive-campaign-highlights/biggive-campaign-highlights.tsx
src/components/biggive-campaign-highlights/readme.md
src/components/biggive-campaign-highlights/test/biggive-campaign-highlights.spec.tsx
src/components/biggive-progress-bar/biggive-progress-bar.tsx
src/components/biggive-progress-bar/readme.md
src/components/biggive-social-icon/readme.md

Aim to reduce run/paint performance problems
while loading cards, especially on Safari

Try campaign cards + progress bars with less dynamic logic

---

angular/projects/components/package.json
package-lock.json
package.json
src/components/biggive-footer/biggive-footer.tsx
src/components/biggive-footer/test/biggive-footer.spec.tsx

DON-599 footer update

---

angular/projects/components/package.json
package-lock.json
package.json
src/components.d.ts
src/components/biggive-header/biggive-header.tsx
src/components/biggive-header/readme.md

DON-681 – give header `closeMenuFromOutside()` method

---

angular/projects/components/package.json
package-lock.json
package.json

If this is approved I'll merge and tag the merge commit as v1.0.180

Update version to 1.0.180

---

angular/projects/components/package.json
package-lock.json
package.json

I'll tag the merge if this is approved.

COM-22: Update version to 1.0.193

---

src/components.d.ts
src/components/biggive-page-section/biggive-page-section.scss
src/components/biggive-page-section/biggive-page-section.tsx
src/components/biggive-page-section/readme.md

This should enable https://github.com/thebiggive/donate-frontend/pull/881

DON-572: Allow bleeding primary colour left and right from section

---

src/globals/mixins.scss

New hover state in context on the donate footer:

COM-49: Make white button green / black on hover

---

src/components/biggive-main-menu/biggive-main-menu.scss

This should have been commited with the last PR. Was used in the screenshot on the PR but then I failed to commit

DON-739: Space out further

---

src/components.d.ts
src/components/biggive-heading/biggive-heading.scss
src/components/biggive-heading/biggive-heading.tsx
src/components/biggive-heading/readme.md
src/components/biggive-heading/test/biggive-heading.spec.tsx
src/globals/heading-size.ts
src/globals/heading-tag.ts
src/globals/spacing-option.ts
src/globals/variables.scss

1. Added ability to colour icon
2. Setup defined options on colours, heading tags, spacing

COM-42 Heading component changes

---

src/components/biggive-main-menu/biggive-main-menu.scss
src/components/biggive-main-menu/biggive-main-menu.tsx
src/components/biggive-main-menu/test/biggive-main-menu.spec.tsx

Update to fix main menu on scroll. https://thebiggive.atlassian.net/browse/COM-35

Fixed Main Menu update

---

.circleci/config.yml
readme.md

And update readme info on branches + versions

Deploy `develop` to Staging Storybook

---

src/components/biggive-campaign-card/biggive-campaign-card.tsx
src/components/biggive-campaign-card/test/biggive-campaign-card.spec.tsx

Not sure if this needs to go into `develop` before going to main.

Don 770 fix donate button click

---

src/components/biggive-form-field-select/biggive-form-field-select.tsx
src/globals/mixins.scss

This is intented to correct the white to grey in the country drop down used in https://github.com/thebiggive/donate-frontend/pull/1118
To show the effect I've made one of the drop downs grey in the filter grid component, but not committed that change:

Don 610 grey drop down

---

src/components/biggive-campaign-card-filter-grid/biggive-campaign-card-filter-grid.scss
src/components/biggive-form-field-select/biggive-form-field-select.scss
src/components/biggive-form-field-select/biggive-form-field-select.tsx
src/components/biggive-form-field-select/test/biggive-form-field-select.spec.tsx

- Remove margin top (moved to filter grid component)
- Add position relative on container to make absolutely positioned prompt element work
No visible changes to how the filter grid component renders.

DON-610: Tweak select component to work in donation stepper:

---

src/components/biggive-branded-image/biggive-branded-image.scss

* Fix "slug" overlapping banner at the top
* Reduce overlap of charity logo & banner at the bottom

COM-58 – simplify + improve `<biggive-branded-image/>` spacing

---

package-lock.json
package.json

Latest stable tag 20.7.* probably targets a minor version which the CircleCI orb doesn't have yet?

Try puppeteer that supports the latest *stable* Chrome 114

---

.circleci/config.yml
package-lock.json
package.json

Use browser tools orb to install Chrome & Chromium and turn off auto-installation on `npm install`.

Try to stabilise Chromium / puppeteer installation

---

.circleci/config.yml

* Use `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD` var
* Don't use deps cache on the `test` job

Try to sort missing Chrome puppeteer glitches

---

angular/package.json
package-lock.json
package.json

DON-836 – support Angular 16

---

src/components.d.ts
src/components/biggive-button/readme.md
src/components/biggive-cookie-banner/biggive-cookie-banner.scss
src/components/biggive-cookie-banner/biggive-cookie-banner.tsx
src/components/biggive-cookie-banner/readme.md
src/components/biggive-cookie-banner/test/biggive-cookie-banner.e2e.ts
src/index.html

Just the display for now, no functionality.

DON-783: First draft of cookie consent initial banner

---

.circleci/config.yml

And tidy up remaining Staging config.

COM-88 – cache Angular build libraries on deploys & regular ones on `test` too

---

src/components.d.ts
src/components/biggive-cookie-banner/biggive-cookie-banner.scss
src/components/biggive-cookie-banner/biggive-cookie-banner.tsx
src/components/biggive-cookie-banner/readme.md

As discussed on Jira.
I've also set it so that if you zoom in (or have a tiny screen) and so the text doesn't fit a scroll bar automatically appears:

DON-783: Add third radio to cooke consent banner, change cookie copy

---

src/components/biggive-campaign-card/biggive-campaign-card.scss
src/components/biggive-campaign-card/biggive-campaign-card.tsx
src/components/biggive-campaign-card/test/biggive-campaign-card.spec.tsx
src/index.html

DON-910: Align "Donate Now" buttons on campaign cards

---

.eslintrc.json
src/components/biggive-campaign-card-filter-grid/biggive-campaign-card-filter-grid.tsx

I haven't 100% confirmed that this works correctly with donate-frontend, but from testing by editing the components index.html it seems to be working. May have to do a components release and then pull into frontend to test further

DON-924: Show selected filters on page load

---

.eslintrc.json
src/components/biggive-campaign-card-filter-grid/biggive-campaign-card-filter-grid.tsx

Reverts thebiggive/components#327
That made the explore page more broken not less broken. Needs another go.

Revert "DON-924: Show selected filters on page load"

---

.eslintrc.json
src/components/biggive-campaign-card-filter-grid/biggive-campaign-card-filter-grid.tsx

Previous version didn't quite work when tested inside donate-frontend
You may want to compare this branch to the previous one that failed. Diff here: https://github.com/thebiggive/components/compare/141da5b22b44137e..DON-924-selected-filters-ii

DON-924: Show selected filters on page load take 2

---

src/components/biggive-totalizer/biggive-totalizer.tsx

Before:
Narrow screen: [Screencast from 2024-02-14 16-03-33.webm](https://github.com/thebiggive/components/assets/159481/c0b8d273-1ea1-4dde-9b32-7ac513bec6fe)
Wide screen:  [Screencast from 2024-02-14 16-04-50.webm](https://github.com/thebiggive/components/assets/159481/592037b3-f313-4207-8d54-00a507852906)
------------------------
After
Narrow screen: [Screencast from 2024-02-14 16-01-11.webm](https://github.com/thebiggive/components/assets/159481/b040f52f-da06-4eaf-87e4-562d24d33124)
Wide screen: [Screencast from 2024-02-14 16-06-13.webm](https://github.com/thebiggive/components/assets/159481/8f6c9dfd-2fe2-49fa-b5ca-bfa7612a4b26)

Don 956 decrease ticker speed

---

src/globals/variables.scss
src/index.html

Please do matching search and replace change when pulling this into frontend

WPD-153: Change background colour to match brand guidelines and WP site

---

package-lock.json
package.json

Reverts thebiggive/components#473

Revert "Bump the all-dependencies group with 12 updates"

---

src/components.d.ts
src/components/biggive-campaign-card-filter-grid/biggive-campaign-card-filter-grid.tsx

Getting failure to build when trying to use this package version in frontend

DON-1057: Export type that seems to be needed

---

src/components/biggive-text-input/biggive-text-input.scss
src/components/biggive-text-input/biggive-text-input.tsx
src/index.html

COM-99 – Coral border for focused biggive-text-input

---

.circleci/config.yml
angular/package.json
angular/projects/components/package.json

While also allowing 17.3.x for now

DON-1075 – Build with & support Angular 18

---

src/components/biggive-hero-image/biggive-hero-image.tsx

COM-102: Adjust size of rectangular hero image to cover background, not

---

package-lock.json
package.json
src/util/fontawesome-icons.ts

Before (on local npm run of components library index):
After:

COM-101: Fix error logs about trailing commas in FontAwesome SVG paths

---

src/components.d.ts
src/components/biggive-campaign-card-filter-grid/biggive-campaign-card-filter-grid.tsx
src/components/biggive-main-menu/biggive-main-menu.scss
src/components/biggive-main-menu/biggive-main-menu.tsx
src/components/biggive-main-menu/readme.md
src/globals/variables.scss
src/index.html

The code is horrible looking and really needs cleaning up but I thought before doing that it'd be worth getting feedback on the appearance of the new menu. See screen recording below showing interaction in Firefox with responsive mode on and off.
[Screencast from 2024-12-16 16-37-29.webm](https://github.com/user-attachments/assets/c08784bf-da76-4064-a71f-9834d061bfdf)

Don 1065 my account submenu wip

---

.eslintignore
.eslintrc.json
angular/package.json
eslint.config.mjs
package-lock.json
package.json
src/components/biggive-hero-image/test/biggive-hero-image.spec.tsx

And `npm update`
Hoping to address unexplained performance regressions in Donate

Pin Stencil to 4.23.* for now

---

.circleci/config.yml

This reverts commit f2aaedabacd06dea4768ead0172213300f6c361b.

Revert "COM-104: Temporarily stop angular build"

---

src/components/biggive-button/biggive-button.scss
src/globals/mixins.scss

Should make basic cards closer to design

COM-104 – slightly reduce PhilCo button font size

---

src/components/biggive-article-card/biggive-article-card.tsx
src/components/biggive-article-card/test/biggive-article-card.spec.tsx
src/components/biggive-footer/biggive-footer.scss

* Fix BG bottom of footer style regression from earlier today
* Fix pointless article card background image attrs

REG-30 a11y fixes

---

src/globals/mixins.scss
src/pages/philco.html

And tidy up line spacing for PhilCo body text

WPD-195 – reduce excess margin around PhilCo headings

---

.github/dependabot.yml
.storybook/main.js
.storybook/preview.js
package-lock.json
package.json
src/components.d.ts

Including auto migrations: "upgradeStorybookRelatedDependencies, consolidated-imports, removeAddonInteractions, remove-essentials"
Includes getting rid of now-empty "essentials" addon collection. And switching from webpack to vite server.

Upgrade to Storybook v9

---

.circleci/config.yml
angular/angular.json
angular/package.json
angular/projects/components/package.json
angular/projects/components/src/lib/components.module.ts
angular/tsconfig.json
package-lock.json
package.json
stencil.config.ts

Keeping peer support for Angular 19 and 20 for now.

DON-1147 – update components to Angular 20

---

.github/dependabot.yml
.storybook/main.js
.storybook/preview.js
package-lock.json
package.json
src/components.d.ts
src/components/biggive-footer/biggive-footer.tsx
src/components/biggive-footer/readme.md

Just in case Angular config was somehow implicated in vite behaving oddly in Production.
Also remove small charities week feature flag

Storybook v9 – retry

---

.github/dependabot.yml
.storybook/main.js
.storybook/preview.js
package-lock.json
package.json
src/components.d.ts
src/components/biggive-footer/biggive-footer.tsx
src/components/biggive-footer/readme.md

Reverts thebiggive/components#780

Revert "Storybook v9 – retry"

---

src/components/biggive-footer/biggive-footer.tsx
src/components/biggive-main-menu/biggive-main-menu.tsx
src/components/biggive-main-menu/test/biggive-main-menu.spec.tsx

I have now moved the page on the staging and prod wordpress sites, so we can update the link.

COM-105: Complete GMF -> Earth Raise rebrand

---

src/components/biggive-heading-banner/biggive-heading-banner.tsx

Not sure if this changes anything for the user other than stopping an error message appearing in browser console.

DON-1120: Fix crash in initial render of banner component
